### ISSUE TITLE
Do you plan to support this package or this is just an experiment what is possible?

### ISSUE THREAD

**Issue by vkhobor** [gomoni/it#12]

**Comment by vyskocilm** [comment]
Hi,

I never had any plans related to `it`. And keep in mind it got partially deprecated by `slices` in a meanwhile. https://cs.opensource.google/go/go/+/refs/tags/go1.23rc2:src/slices/iter.go

 * `slices.All` is `it.Index`
 * `slices.Values` is `it.FromSlice`
 * `slices.Backward` is `it.Reverse`

And so on. So until `it` will get ported to 1.23 I'd not consider it stable. Then we can freeze the API and declare it stable. Does it answer your question?

**Comment by vkhobor** [comment]
Thank you. Yes I think. I used [samber/lo](https://github.com/samber/lo) before for general transforming slices and so. I was wondering what package should I use after 1.23 gets released.
There is this discussion on `samber/lo` https://github.com/samber/lo/pull/439 or I could use your package.

**Comment by vyskocilm** [comment]
Rebased the library on top of go 1.23 stdlib. Moved helper functions to `it/islices` and `it/imaps` to mimic the structure of a standard library.

The API itself is minimal and can remain stable as the iterator support got stabilized in Go.

Feel free to open a new issue with any problem you'll find.
