### ISSUE TITLE
Mappable vs Mapable

### ISSUE THREAD

**Issue by wkhere** [gomoni/it#16]
Hi!

Your API has `Mapable` while it's spelled `Mappable` in your readme, so there seems to be confusion about the proper form. English is not my native language so I am not sure, Mappable looks more correct. Plus this: https://en.wiktionary.org/wiki/mapability "misspelling of mappability".

Do you think it's ok to have yet another API change?

**Comment by vyskocilm** [comment]
Hi,

it's not mine mother tongue as well :-). It looks like the variant with double `p` is the correct: https://en.wiktionary.org/wiki/mappable

As there are no other packages using `it` according pkg.go.dev and no v1 has been released, feel free to sent a PR.

Thanks for looking at this.

**Comment by wkhere** [comment]
Ah yeah, sorry for not closing this issue right away after PR was merged :) all good
